name = "UELAT"
uuid = "b83e4f30-0154-4039-a555-15f3b250231f"
version = "0.2.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.9, 1.10"
FFTW = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b3a"

[targets]
test = ["Test"]
